### ISSUE TITLE
Nagios Spool Location

### ISSUE THREAD

**Issue by kymatica** [Griesbacher/nagflux#26]
Hi,

I have Nagios installed through Check_MK Raw, and I installed Grafana  and InfluxDB separately.

Every time I try and launch nagflux it does not seem to do anything. I am assuming that the NagiosSpoolfileFolder is incorrect in the config.

is there a way to tell what directory nagflux requires?  I can't find a spool value anywhere in Nagios, and I'm unsure of what the contents should be.

Below is the output I get when launching Nagflux:

`
Info: Started Nagflux v0.3.0
Info: Is InfluxDB running: true
Info: Could not detect livestatus version, waiting for 1m0s 2 times( 0/2 )...
Info: Could not detect livestatus version, waiting for 1m0s 2 times( 1/2 )...
Info: Livestatus version:
Warn: Could not detect livestatus type, with version: . Asuming Nagios

`

Thank you

**Comment by Griesbacher** [comment]
Have a look at this post, it's just in German but I think you could guess the commands. It describes how you activate everything if you're using OMD. If that's running you could port it to your setup easily. 
https://labs.consol.de/de/nagios/omd/2015/10/21/activate-nagflux.html

**Comment by kymatica** [comment]
Thank you for the reply!

I gave OMD a try, but it seems to install older versions of some components.  While it does seem to work, it would mean rebuilding my instances on older revisions.

Any hints on trying to find out the correct paths for adding Nagflux to an existing build?

Thanks

**Comment by Griesbacher** [comment]
In Nagios there is this option "service_perfdata_file"/"host_perfdata_file" this could give a hint. But beware in OMD, this file will be copied to another destination, every few seconds. Because of:
``` bash
etc/nagios/conf.d/histou.cfg:21:       command_line    /bin/mv /omd/sites/foo/var/pnp4nagios/service-perfdata /omd/sites/foo/var/pnp4nagios/spool/service-perfdata.$TIMET$

```
 That's the reason I can't give a certain answer.
I've you have already pnp4nagios installed, this uses the same folder to collect the data.

On the second hand, your log does only show that the livestatus config you've put in the config did not work. This could have two reasons, there is no livestatus running, or the livestatus version is not known to nagflux, but this dose not solve the problem.

Also beware that histou(display grafana dashboards like pnp) does one work with thruk.

**Comment by Griesbacher** [comment]
I'll close that one due to inactivity.
